// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProAgil.WebAPI.Data;

namespace ProAgil.WebAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20200330155918_imagemAdd")]
    partial class imagemAdd
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("ProAgil.WebAPI.model.Evento", b =>
                {
                    b.Property<int>("eventoId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("dataEvento");

                    b.Property<string>("imagemUrl");

                    b.Property<string>("local");

                    b.Property<string>("lote");

                    b.Property<int>("qtsPessoas");

                    b.Property<string>("tema");

                    b.HasKey("eventoId");

                    b.ToTable("eventos");
                });
#pragma warning restore 612, 618
        }
    }
}
